server:
  port: 9000

spring:
  application:
    name: book-service

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://booklist-mysql-2.mysql.database.azure.com:3306/flexibleserverdb
    username: rootuser
    password: ${BOOK_LIST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Security
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
